apiVersion: v1
kind: ConfigMap
metadata:
  name: jupyter-{{ .Values.Instance }}-startup
  labels:
    app: {{ template "jupyter.name" . }}
    instance: {{ .Values.Instance | quote }}
data:
  startup_script.sh: |+
    #!/bin/bash
    #
    #sleep 10
    mkdir -p /home/{{ .Values.Jupyter.NB_USER }}/.ssh
    {{ if eq .Values.SSH.Enabled true }}
    echo {{ .Values.SSH.SSH_Public_Key }} > /home/{{ .Values.Jupyter.NB_USER }}/.ssh/authorized_keys
    chmod 0600 /home/{{ .Values.Jupyter.NB_USER }}/.ssh/authorized_keys
    {{ end }}
    chown -R 1000:100 /home/$NB_USER
    {{ if eq .Values.SSH.Enabled true}}
    cat /etc/supervisor/supervisord.d/sshd.conf >> /etc/supervisor/conf.d/supervisord.conf
    {{ end }}
    {{ if eq .Values.CondorConfig.Enabled true}}
    cat /etc/supervisor/supervisord.d/htcondor.conf  >> /etc/supervisor/conf.d/supervisord.conf
    {{ end }}
    /usr/bin/supervisord
