apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "jupyter.fullname" . }}
  labels:
    app: {{ template "jupyter.name" . }}
    chart: {{ template "jupyter.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "jupyter.name" . }}
      chart: {{ template "jupyter.chart" . }}
      release: {{ .Release.Name }}
      instance: {{ .Values.Instance | quote }}
  template:
    metadata:
      labels:
        app: {{ template "jupyter.name" . }}
        chart: {{ template "jupyter.chart" . }}
        release: {{ .Release.Name }}
        instance: {{ .Values.Instance | quote }}
    spec:
      volumes:
      {{ if eq .Values.CondorConfig.Enabled true }}
      - name: condor-token-volume
        secret:
          secretName: {{ .Values.CondorConfig.AuthTokenSecret }}
          items:
          - key: condor_token
            path: condor_token
            mode: 256
          - key: reverse_password
            path: password
            mode: 256
      - name: condor-configuration
        configMap:
          name: jupyter-{{ .Values.Instance }}-condor-configuration
          items:
          - key: condor_config.local
            path: condor_config.local
            mode: 292
      {{ end }}
      - name: jupyter-{{ .Values.Instance }}-startup
        configMap:
          name: jupyter-{{ .Values.Instance }}-startup
          items:
          - key: startup_script.sh
            path: startup_script.sh
            mode: 0755
      - name: jupyter-{{ .Values.Instance }}-motd
        configMap:
          name: jupyter-{{ .Values.Instance }}-motd
          items:
          - key: 99-limits
            path: 99-limits
            mode: 0755
      containers:
      - name: scipy-notebook
        image: slateci/jupyter-condor-centos7:latest
        imagePullPolicy: "Always"
        workingDir: /home/{{ .Values.Jupyter.NB_USER }}
        env:
        - name: JUPYTER_ENABLE_LAB
          value: 'yes'
        - name: NB_USER
          value: {{ .Values.Jupyter.NB_USER | default "jovyan" | quote }}
        {{ if eq .Values.CondorConfig.Enabled true }}
        - name: _CONDOR_TCP_FORWARDING_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: _CONDOR_PRIVATE_NETWORK_INTERFACE
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        {{ end }}
        - name: JupyterPassword
          value: {{ .Values.Jupyter.Password | quote }} 
        - name: JupyterToken
          value: {{ .Values.Jupyter.Token | quote }} 
        readinessProbe:
          tcpSocket:
            port: 8888
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8888
          initialDelaySeconds: 15
          periodSeconds: 30
          failureThreshold: 3
        resources:
          requests:
            # For CPU only, set request as half of limit
            cpu: "{{ div .Values.Resources.CPU 2 }}m"
            memory: "{{ .Values.Resources.Memory }}Mi"
          limits:
            cpu: "{{ .Values.Resources.CPU }}m"
            memory: "{{ .Values.Resources.Memory }}Mi"
        ports:
        - containerPort: 8888
          protocol: TCP
{{ if eq .Values.SSH.Enabled true }}
        - containerPort: 22
          protocol: TCP
{{ end }}
{{ if .Values.CondorConfig.Enabled }}
        - containerPort: {{ .Values.CondorConfig.ExternalCondorPort }}
          protocol: TCP
{{ end }}
        command: ["/usr/bin/startup_script.sh"] 
        volumeMounts:
        {{ if eq .Values.CondorConfig.Enabled true }}
        - name: condor-token-volume
          mountPath: /root/tokens/condor_token
          subPath: condor_token
        - name: condor-token-volume
          mountPath: /etc/condor/passwords.d/{{ .Values.CondorConfig.KeyName }}
          subPath: password
        - name: condor-configuration
          mountPath: /etc/condor/condor_config.local
          subPath: condor_config.local
        {{ end }}
        - name: jupyter-{{ .Values.Instance }}-startup
          mountPath: "/usr/bin/startup_script.sh"
          subPath: startup_script.sh
        - name: jupyter-{{ .Values.Instance }}-motd
          mountPath: "/etc/update-motd.d/99-limits"
          subPath: 99-limits

