apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "jupyter.fullname" . }}
  labels:
    app: {{ template "jupyter.name" . }}
    chart: {{ template "jupyter.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.Ingress.Class }}
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  tls:
  - hosts:
    - {{ .Values.Ingress.Subdomain }}.{{ .Values.SLATE.Cluster.DNSName }}
    secretName: {{ .Values.Instance}}-jupyter-notebook-tls
  rules:
  - host: {{ .Values.Ingress.Subdomain }}.{{ .Values.SLATE.Cluster.DNSName }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "jupyter.fullname" . }}
          servicePort: 8888
