kind: Service
apiVersion: v1
metadata:
  name: {{ template "jupyter.fullname" . }}
spec:
  type: ClusterIP
  selector:
    app: {{ template "jupyter.name" . }}
    chart: {{ template "jupyter.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
