apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "open-ondemand.fullname" . }}
  labels:
    {{- include "open-ondemand.labels" . | nindent 4 }}
    instanceID: {{ .Values.SLATE.Instance.ID | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "open-ondemand.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "open-ondemand.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
        # Shared Volume
        - name: shared-data
          emptyDir: {}
        # Keycloak Startup Script
        - name: keycloak-setup
          configMap:
            name: {{ include "open-ondemand.fullname" . }}-keycloak-setup
        # OnDemand Server Config
        - name: ood-portal-config
          configMap:
            name: {{ include "open-ondemand.fullname" . }}-ood-portal
            items:
            - key: ood_portal.yml
              path: ood_portal.yml
        # LinuxHost Adapter
        - name: linuxhost-adapter
          configMap:
            name: {{ include "open-ondemand.fullname" . }}-host-adapter
        # Secret Volume
        {{ range .Values.clusters }}
        {{ if eq .cluster.desktopEnable true }}
        - name: secret-volume
          secret:
            secretName: ssh-key-secret
        # Desktop Application Files
        - name: desktop-options
          configMap:
            name: {{ include "open-ondemand.fullname" . }}-desktop-options
            items:
              - key: {{ .cluster.name | lower | nospace }}.yml
                path: {{ .cluster.name | lower | nospace }}.yml
        {{ end }}
        {{ end }}
        - name: desktop-global-form
          configMap:
            name: {{ include "open-ondemand.fullname" . }}-desktop-form
            items:
            - key: form.yml
              path: form.yml
        - name: desktop-global-submit
          configMap:
            name: {{ include "open-ondemand.fullname" . }}-desktop-submit
            items:
            - key: submit.yml.erb
              path: submit.yml.erb
        - name: desktop-host-submit
          configMap:
            name: {{ include "open-ondemand.fullname" . }}-desktop-host-submit
        # Claim SLATE volume to persist Keycloak data.
        - name: keycloak-db
          persistentVolumeClaim:
            claimName: keycloak-persistent-volume-{{ .Values.Instance }}
      containers:
        - name: open-ondemand
          image: dockerbox88/open-ondemand:latest
          imagePullPolicy: Always
          volumeMounts:
            # Shared Volume
            - name: shared-data
              mountPath: /shared
            # OnDemand Server Config
            - name: ood-portal-config
              mountPath: /etc/ood/config/ood_portal.yml
              subPath: ood_portal.yml
            # LinuxHost Adapter
            - name: linuxhost-adapter
              mountPath: /etc/ood/config/clusters.d
            # Secret Volume
            - name: secret-volume
              readOnly: true
              mountPath: "/etc/ssh"
            # Desktop Application Files
            - name: desktop-options
            {{ range .Values.clusters }}
            {{ if eq .cluster.desktopEnable true }}
              mountPath: /etc/ood/config/apps/bc_desktop/{{ .cluster.name | lower | nospace }}.yml
              subPath: {{ .cluster.name | lower | nospace }}.yml
            {{ end }}
            {{ end }}
            - name: desktop-global-form
              mountPath: /var/www/ood/apps/sys/bc_desktop/form.yml
              subPath: form.yml
            - name: desktop-global-submit
              mountPath: /var/www/ood/apps/sys/bc_desktop/submit.yml.erb
              subPath: submit.yml.erb
            - name: desktop-host-submit
              mountPath: /etc/ood/config/apps/bc_desktop/submit
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: SLATE_INSTANCE_NAME
              value: {{ .Values.Instance }}
            - name: SLATE_CLUSTER_NAME
              value: {{ .Values.SLATE.Cluster.DNSName }}
        - name: keycloak
          image: jboss/keycloak:4.8.3.Final
          imagePullPolicy: Always
          # Run script if setupKeycloak parameter is enabled.
          {{ if eq .Values.setupKeycloak true }}
          lifecycle:
            postStart:
              exec:
                command: ["/bin/bash", "/etc/keycloak/keycloak-setup.sh"]
          {{ end }}
          volumeMounts:
            - name: shared-data
              mountPath: /shared
            - name: keycloak-setup
              mountPath: /etc/keycloak/
              # Mount SLATE volume to the location of the Keycloak database.
            - name: keycloak-db
              mountPath: "/opt/jboss/keycloak/standalone/data"
          env:
            - name: PROXY_ADDRESS_FORWARDING
              value: "true" 
              # Set Keycloak default username and password
            - name: KEYCLOAK_USER
              value: "admin"
            - name: KEYCLOAK_PASSWORD
              value: {{ randAlphaNum 12 | b64enc | quote }}
              # Specify database type (default Java H2 database)
            - name: DB_VENDOR 
              value: "h2"
            - name: SLATE_INSTANCE_NAME
              value: {{ .Values.Instance }}
            - name: SLATE_CLUSTER_NAME
              value: {{ .Values.SLATE.Cluster.DNSName }}
            - name: SLATE_SETUP_LDAP
              value: {{ .Values.setupLDAP | quote }}
          ports:
            - name: kc8080
              containerPort: 8080
              protocol: TCP
---