apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "open-ondemand.fullname" . }}-desktop-host-submit-configmap.yaml
data:

  {{ range .Values.clusters }}
  {{ if eq .cluster.desktopEnable true }}
  linuxhost_submit.yml.erb: |
    ---
    batch_connect:
      template: "vnc"
      native:
        singularity_bindpath: {{ .cluster.job.singularity_bindpath }}
        singularity_container: {{ .cluster.job.singularity_image }}
  {{ end }}
  {{ end }}