apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "open-ondemand.fullname" . }}-desktop-form
data:

  {{ range .Values.clusters }}
  form.yml: |
  ---
  attributes:
    desktop: "mate"
    bc_vnc_idle: 0
    bc_vnc_resolution:
      required: true
    node_type: null
    cluster:
      widget: "select"
      options:
        {{- $cluster.name | quote }}
  
  form:
    - bc_vnc_idle
    - desktop
    - bc_account
    - bc_num_hours
    - bc_num_slots
    - node_type
    - bc_queue
    - bc_vnc_resolution
    - bc_email_on_started
  {{ end }}
