apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "open-ondemand.fullname" . }}-desktop-host
data:
  {{ range .Values.clusters }}
  cluster-{{ .cluster.name | lower | nospace }}.yml: |
    ---
    title: "{{ .cluster.name }} desktop"
    cluster: {{ .cluster.name | quote }}
    submit: "linux_host"
    attributes:
      bc_queue: null
      bc_account: null
      num_cores: none
  {{ end }}
