apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "open-ondemand.fullname" . }}-hostbased-auth
data:
  hostbased.sh: |
    #!/bin/bash
    cat /root/{{ .Values.host_key | lower | nospace}}.pub >> \
    /etc/ssh/{{ .Values.host_key | lower | nospace}}.pub && \
    chmod 0640 /etc/ssh/{{ .Values.host_key | lower | nospace}}.pub
    groupmod -g {{ .Values.ssh_keys_GID }} ssh_keys
    chgrp ssh_keys /etc/ssh/{{ .Values.host_key | lower | nospace}}.pub
