apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "open-ondemand.fullname" . }}-shell-setup
data:

  {{ range .Values.clusters }}
  cluster-{{ .cluster.name | lower | nospace }}.yml: |
    ---
    v2:
      metadata:
        title: {{ .cluster.name | quote }}
        priority: 2
      login:
        host: {{ .cluster.host | quote }}
      job: {{ .cluster.job | quote }}
#      batch_connect:
#        basic:
#          script_wrapper: |
#           #!/bin/bash
#            ###### your_script_here ######
#        vnc:
#          script_wrapper: |
#            #!/bin/bash
#            ###### your_vnc_startup_here ######
  {{ end }}
