apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "postgresql.fullname" . }}
  labels:
    app: {{ template "postgresql.name" . }}
    chart: {{ template "postgresql.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "postgresql.name" . }}
      instance: {{ .Values.Instance | quote }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "postgresql.name" . }}
        chart: {{ template "postgresql.chart" . }}
        instance: {{ .Values.Instance | quote }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: postgresql
        image: "bitnami/postgresql:latest"
        imagePullPolicy: Always
        volumeMounts:
        - name: # TODO postgresql-{{ .Values.Instance }}-configuration
          mountPath: # TODO /usr/share/postgresql/html
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
      restartPolicy: Always
      # TODO
      volumes:
      - name: postgresql-{{ .Values.Instance }}-configuration
        configMap:
          name: postgresql-{{ .Values.Instance }}-configuration
