apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "postgresql.fullname" . }}
  labels:
    app: {{ template "postgresql.name" . }}
    chart: {{ template "postgresql.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "postgresql.name" . }}
      instance: {{ .Values.Instance | quote }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "postgresql.name" . }}
        chart: {{ template "postgresql.chart" . }}
        instance: {{ .Values.Instance | quote }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: postgresql
        image: "bitnami/postgresql:latest"
        imagePullPolicy: Always
        env:
          - name: POSTGRESQL_PASSWORD
            value: {{ .Values.adminPassword | quote }} 
        # Mount SLATE volume to persist data.
        volumeMounts:
          - name: postgresql-db
            mountPath: /bitnami/postgresql
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
      restartPolicy: Always
      volumes:
        # Claim previously-allocated SLATE volume.
      - name: postgresql-db
        persistentVolumeClaim:
          claimName: {{ .Values.claimName }}

