# Open OnDemand Configuration
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# The SLATE instance value.
Instance: "global"

replicaCount: 1

setupKeycloak: true

# SLATE volume to claim
claimName: keycloak-db

### SLATE-START ###
SLATE:
  Instance:
    ID: "untagged"
  Cluster:
    DNSName: "utah-dev.slateci.net"
### SLATE-END ###

# LDAP/Kerberos setup and configuration
setupLDAP: true
ldap:
  connectionURL: "ldap://ldap.chpc.utah.edu"
  importUsers: "true"
  rdnLDAPAttribute:  "uid"
  uuidLDAPAttribute: "uidNumber"
  userObjectClasses: "inetOrgPerson, organizationalPerson"
  usersDN: "ou=People,dc=chpc,dc=utah,dc=edu"
kerberos:
  realm: "AD.UTAH.EDU"
  serverPrincipal: "HTTP/utah-dev.chpc.utah.edu@AD.UTAH.EDU"
  keyTab: "/etc/krb5.keytab"
  kerberosPasswordAuth: "true"
  debug: "true"

# Shell application setup
# Add another cluster section for each backend cluster you wish to connect to
clusters:
  - cluster:
      name: "Kingspeak"
      host: "kingspeak.chpc.utah.edu"
      job: |
        adapter: "linux_host"
        submit_host: "{{ .cluster.name | quote }}"
        ssh_hosts:
          - node1.slateci.net
          - node2.slateci.net
        site_timeout: 7200
        debug: true
        singularity_bin: /path/to/your/singularity
        singularity_bindpath: /etc,/media,/mnt,/opt,/run,/srv,/usr,/var,/users
        singularity_image: /path/to/your/image.sif  # Something like centos_7.6.sif
        # If strict_host_checking is enabled then any unlisted nodes may cause adapter to fail round-robin
        strict_host_checking: false
        tmux_bin: /path/to/your/tmux
  - cluster:
      name: "Notchpeak"
      host: "notchpeak.chpc.utah.edu"
      job: |
        adapter: "linux_host"
        submit_host: "{{ .cluster.name | quote }}"
        ssh_hosts:
          - node1.slateci.net
          - node2.slateci.net
        site_timeout: 7200
        debug: true
        singularity_bin: /path/to/your/singularity
        singularity_bindpath: /etc,/media,/mnt,/opt,/run,/srv,/usr,/var,/users
        singularity_image: /path/to/your/image.sif  # Something like centos_7.6.sif
        # If strict_host_checking is enabled then any unlisted nodes may cause adapter to fail round-robin
        strict_host_checking: false
        tmux_bin: /path/to/your/tmux
