# Open OnDemand Configuration
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# The SLATE instance value.
Instance: "global"

replicaCount: 1

setupKeycloak: true

# Keycloak volume parameters
volume:
  storageClass: local-path
  size: 50M

# LDAP/Kerberos setup and configuration
setupLDAP: true
ldap:
  connectionURL: "ldap://ldap.chpc.utah.edu"
  importUsers: "true"
  rdnLDAPAttribute:  "uid"
  uuidLDAPAttribute: "uidNumber"
  userObjectClasses: "inetOrgPerson, organizationalPerson"
  usersDN: "ou=People,dc=chpc,dc=utah,dc=edu"
kerberos:
  realm: "AD.UTAH.EDU"
  serverPrincipal: "HTTP/utah-dev.chpc.utah.edu@AD.UTAH.EDU"
  keyTab: "/etc/krb5.keytab"
  kerberosPasswordAuth: "true"
  debug: "true"

# Configure LinuxHost Adapter or Shell Application
# Add another cluster section for each backend cluster you wish to connect to
clusters:
  - cluster:
      name: "slate-node1"
      host: "slate-node1.chpc.utah.edu"
      desktopEnable: true
      job:
        ssh_hosts: "slate-node1.chpc.utah.edu"
        singularity_bin: /bin/singularity
        singularity_bindpath: /etc,/media,/mnt,/opt,/run,/srv,/usr,/var,/home
        singularity_image: /opt/centos7.sif  # Something like centos_7.6.sif
        tmux_bin: /bin/tmux
      basic_script: 
        - "#!/bin/bash"
        - "module purge"
        - "export XDG_RUNTIME_DIR=$(mktemp -d)"
        - "%s"
      vnc_script: 
        - "#!/bin/bash"
        - "module purge"
        - "export PATH='/opt/TurboVNC/bin:$PATH'"
        - "export WEBSOCKIFY_CMD='/usr/bin/websockify'"
        - export XDG_RUNTIME_DIR=$(mktemp -d)"
        - "%s"
      set_host: "$(hostname)"
  - cluster:
      name: "Notchpeak"
      host: "notchpeak.chpc.utah.edu"
      desktopEnable: false

# Choose a desktop installed on the remote host (mate 1+, xfce 4+, Gnome 2)
desktop: "mate"

# Choose a regular expression that catches all accessible clusters
host_regex: '[\w.-]+\.(peaks|arches|int.chpc.utah.edu|chpc.utah.edu)'

# Name the host_keys stored in your ssh-key-secret
host_keys:
  - host_key: 
      name: "ssh_host_ecdsa_key"
  - host_key:
      name: "ssh_host_ecdsa_key.pub"
  - host_key: 
      name: "ssh_host_ed25519_key"
  - host_key:
      name: "ssh_host_ed25519_key.pub"
  - host_key: 
      name: "ssh_host_rsa_key"
  - host_key:
      name: "ssh_host_rsa_key.pub"

# Specify a label for the nodeSelector, this will assign OnDemand to a node with a matching label
node_selector_label: "ssd"

# Name the group ID for the ssh_keys group on your host system
ssh_keys_GID: 993

# Enable NFS sharing to the container
ip_addr: 155.101.6.140
nfs_path: "/home"

# Configure additional test users to be added to Keycloak.
testUsers:
  - user:
      name: "test"
      tempPassword: "test"

### SLATE-START ###
SLATE:
  Instance:
    ID: "untagged"
  Cluster:
    DNSName: "utah-dev.slateci.net"
### SLATE-END ###
      
