apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "basic-auth.fullname" . }}
  labels:
    app: {{ template "basic-auth.name" . }}
    chart: {{ template "basic-auth.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "basic-auth.name" . }}
      instance: {{ .Values.Instance | quote }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "basic-auth.name" . }}
        chart: {{ template "basic-auth.chart" . }}
        instance: {{ .Values.Instance | quote }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: basic-auth
        image: "basic-auth:latest"
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
      restartPolicy: Always
