apiVersion: v1
kind: ConfigMap
metadata:
  name: connect-submit-node-{{ .Values.Instance }}-condor-configuration
  labels:
    app: connect-submit-node
    instance: {{ .Values.Instance }}
data:
  condor_config.local: |+
{{ .Values.CondorConfig.ConfigFile | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: connect-submit-node-{{ .Values.Instance }}-provisioner-configuration
  labels:
    app: connect-submit-node
    instance: {{ .Values.Instance }}
data:
  config: |+
    #!/bin/sh
    # This file will be sourced before the CI Connect provisioner starts up. You
    # can add anything you like here.

    # Append PATH
    # Apparently '[ -z "$PATH" ]' doesn't work because of some subtlety where Bash 
    # kind-of-sort-of says $PATH is set, even though it doesn't appear in `env`
    export PATH="$PATH:/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin"
    
    export INNER_GROUP="{{ .Values.UserConfig.ConnectInnerGroup }}"
    export OUTER_GROUP="{{ .Values.UserConfig.ConnectOuterGroup }}"
