#apiVersion: v1
#kind: Service
#metadata:
#  name: {{ template "connect-submit-node.fullname" . }}
#  labels:
#    app: {{ template "connect-submit-node.fullname" . }}
#    chart: {{ template "connect-submit-node.chart" . }}
#    release: {{ .Release.Name }}
#    instance: {{ .Values.Instance }}
#spec:
#  type: NodePort
#  ports:
#  - port: 2222
#    protocol: TCP 
#  selector:
#    app: {{ template "connect-submit-node.fullname" . }}
#    instance: {{ .Values.Instance }}
