apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: policy-demo 
  namespace: default
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - ipBlock:
        cidr: 155.101.8.34/32 
