{{ if .Values.NetworkPolicy.Enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "nginx-fullname" . }}
  labels:
    app: {{ template "nginx.name" . }}
    chart: {{ template "nginx.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "nginx.name" . }}
      chart: {{ template "nginx.chart" . }}
      release: {{ .Release.Name }}
      instance: {{ .Values.Instance | quote }}
  policyTypes:
  - Ingress
  - Egress
  egress:
  - to:
    - ipBlock:
        cidr: {{ .Values.NetworkPolicy.AllowedCIDR }}
  ingress:
  - from:
    - ipBlock:
        cidr: {{ .Values.NetworkPolicy.AllowedCIDR }}
{{ end }}
---
{{ if not .Values.NetworkPolicy.Enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ template "nginx-fullname" . }}
  labels:
    app: {{ template "nginx.name" . }}
    chart: {{ template "nginx.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "nginx.name" . }}
      chart: {{ template "nginx.chart" . }}
      release: {{ .Release.Name }}
      instance: {{ .Values.Instance | quote }}
  policyTypes:
  - Ingress
  - Egress
  egress:
  - {}
  ingress:
  - {}
{{ end }}
