{{ if .Values.CondorConfig.ConfigFile }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "condor-submit.name" . }}-condor-configuration
  labels:
    app: condor-submit
    instance: {{ .Values.Instance | quote}}
data:
  condor_config.local: |+
    COLLECTOR_HOST = {{ .Values.CondorConfig.CollectorHost }}
    COLLECTOR_PORT = {{ .Values.CondorConfig.CollectorPort }}
{{ .Values.CondorConfig.ConfigFile  | indent 4 }}
---
{{ end }}
{{ if eq .Values.UserConfig.Mode connectapi }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "condor-submit.name" . }}-provisioner-configuration
  labels:
    app: condor-submit
    instance: {{ .Values.Instance | quote }}
data:
  config: |+
    #!/bin/sh
    # This file will be sourced before the CI Connect provisioner starts up. You
    # can add anything you like here.
    # Append PATH
    # Apparently '[ -z "$PATH" ]' doesn't work because of some subtlety where Bash 
    # kind-of-sort-of says $PATH is set, even though it doesn't appear in `env`
    export PATH="$PATH:/bin:/usr/bin:/usr/local/bin:/sbin:/usr/sbin:/usr/local/sbin"
    export INNER_GROUP="{{ .Values.UserConfig.ConnectInnerGroup }}"
    export OUTER_GROUP="{{ .Values.UserConfig.ConnectOuterGroup }}"
---
{{ end }}
{{ if eq .Values.UserConfig.Mode sssd }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "condor-submit.name" . }}-auth-configuration
  labels:
    app: condor-submit
    instance: {{ .Values.Instance | quote }}
data:
  sssd.conf: |+
{{ .Values.sssd | indent 4 }}
{{ end }}
