{{ required "CondorConfig.CollectorHost must be set" .Values.CondorConfig.CollectorHost }}
{{ required "CondorConfig.CollectorPort must be set" .Values.CondorConfig.CollectorPort }}
{{ required "CondorConfig.AuthTokenSecret must be set" .Values.CondorConfig.AuthTokenSecret }}
{{ if and .Values.SystemConfig.HostPath .Values.SystemConfig.PVCName }}
  {{ required "SystemConfig.HostPath and SystemConfig.PVCName should not both be set" .Values.Error_DoNotSet }}
{{ end }}
{{ if or .Values.SystemConfig.HostPath .Values.SystemConfig.PVCName }}
  {{ required "SystemConfig.MountLocation must be set if SystemConfig.HostPath or SystemConfig.PVCName is set" .Values.SystemConfig.MountLocation }}
{{ end }}
{{ if eq .Values.UserConfig.Mode "connectapi" }}
  {{ required "UserConfig.ConnectToken must be set when using UserConfig.Mode 'connectapi'" .Values.UserConfig.ConnectToken }}
  {{ required "UserConfig.ConnectUserSourceGroup must be set when using UserConfig.Mode 'connectapi'" .Values.UserConfig.ConnectUserSourceGroup }}
  {{ required "UserConfig.ConnectGroupSourceGroup must be set when using UserConfig.Mode 'connectapi'" .Values.UserConfig.ConnectGroupSourceGroup }}
{{ end }}