apiVersion: v1
kind: Service
metadata:
 name: {{ template "condor-submit.fullname" . }}
 labels:
   app: {{ template "condor-submit.fullname" . }}
   chart: {{ template "condor-submit.chart" . }}
   release: {{ .Release.Name }}
   instance: {{ .Values.Instance | quote }}
spec:
 type: NodePort
 ports:
 - port: 22
   protocol: TCP
   name: ssh
 - port: {{ .Values.ExternalCondorPort }}
   protocol: TCP
   name: condor
   nodePort: {{ .Values.ExternalCondorPort }}
 selector:
   app: {{ template "condor-submit.fullname" . }}
   instance: {{ .Values.Instance | quote }}