apiVersion: v1
kind: ConfigMap
metadata:
  name: osg-hosted-ce-{{ .Values.Instance }}-configuration
  labels:
    app: osg-hosted-ce
    chart: {{ template "osg-hosted-ce.chart" . }}
    instance: {{ .Values.Instance }}
    release: {{ .Release.Name }}
data:
  99-local.ini: |
    [Site Information]
    group = {{ .Values.Site.Group }}
    host_name = localhost
    resource = {{ .Values.Site.Resource }}
    resource_group = {{ .Values.Site.ResourceGroup }}
    sponsor = {{ .Values.Site.Sponsor }}
    site_policy = UNAVAILABLE
    contact = {{ .Values.Site.Contact }}
    email = {{ .Values.Site.ContactEmail }}
    city = {{ .Values.Site.City }}
    country = {{ .Values.Site.Country }}
    latitude = {{ .Values.Site.Latitude }}
    longitude = {{ .Values.Site.Longitude }}

    [BOSCO]
    enabled = True
    users = {{ .Values.Cluster.Users }}
    endpoint =  {{ .Values.Cluster.Endpoint }}
    batch =  {{ .Values.Cluster.Batch }}
    ssh_key = /etc/osg/bosco.key
    max_jobs = {{ .Values.Cluster.MaxJobs }}

    [Misc Services]
    edit_lcmaps_db = True
    authorization_method = vomsmap

    [Storage]
    se_available = False
    default_se = None
    grid_dir = {{ .Values.Storage.GridDir }}
    app_dir = UNSET
    data_dir = None
    worker_node_temp = {{ .Values.Storage.WorkerNodeTemp }}

    [Subcluster {{ .Values.Subcluster.Name }}]
    name = {{ .Values.Subcluster.Name }}
    ram_mb = {{ .Values.Subcluster.Memory }}
    cores_per_node = {{ .Values.Subcluster.CoresPerNode }}
    max_wall_time = {{ .Values.Subcluster.MaxWallTime }}
    allowed_vos = {{ .Values.Subcluster.AllowedVOs }}

    [Squid]
    enabled = {{ .Values.Squid.Enabled }} 
    location =  {{ .Values.Squid.Location }}
    policy = DEFAULT
    cache_size = DEFAULT
    memory_size = DEFAULT
{{ if .Values.GridmapOverride }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: osg-hosted-ce-{{ .Values.Instance }}-grid-mapfile
  labels:
    app: osg-hosted-ce
    chart: {{ template "osg-hosted-ce.chart" . }}
    instance: {{ .Values.Instance }}
    release: {{ .Release.Name }}
data:
  grid-mapfile: |+
{{ .Values.GridmapOverride | indent 4 }}
{{ end }}
{{ if .Values.CustomizationScript }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: osg-hosted-ce-{{ .Values.Instance }}-cluster-configuration
  labels:
    app: osg-hosted-ce
    chart: {{ template "osg-hosted-ce.chart" . }}
    instance: {{ .Values.Instance }}
    release: {{ .Release.Name }}
data:
  {{ .Values.Cluster.Batch }}_local_submit_attributes.sh: |+
{{ .Values.CustomizationScript | indent 4 }}
{{ end }}
{{ if .Values.HTTPLogger.Enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: osg-hosted-ce-{{ .Values.Instance }}-logger-startup
  labels:
    app: osg-hosted-ce
    chart: {{ template "osg-hosted-ce.chart" . }}
    instance: {{ .Values.Instance }}
    release: {{ .Release.Name }}
data:
  start-nginx.sh: |+
    #!/bin/bash -e
    
    apt-get update
    apt-get install openssl -y
  
    if [ -z $HTPASSWD ]; then
      PASS=$(tr -dc 'a-f0-9' < /dev/urandom | head -c16)
      echo "Your randomly generated logger credentials are"
      echo "**********************************************"
      echo "logger:$PASS"
      echo "**********************************************"
      HTPASSWD="$(openssl passwd -apr1 $(echo -n $PASS))"
    fi
  
    # maybe validate this
    mkdir -p /etc/nginx/auth
    echo "logger:$HTPASSWD" > /etc/nginx/auth/htpasswd

    echo 'server {
      listen       8080;
      server_name  localhost;
      location / {
        default_type text/plain;
        auth_basic "Restricted";
        auth_basic_user_file /etc/nginx/auth/htpasswd;  
        root   /usr/share/nginx/html;
        autoindex  on;
      }
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
        root   /usr/share/nginx/html;
      }
    }' > /etc/nginx/conf.d/default.conf
    exec nginx -g 'daemon off;'

{{ end }}
