# Default values for perfsonar-testpoint.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

Instance: ''

NodeSelection:  
  Hostname: null
HTTPLogger: 
  Enabled: false
### SLATE-START ###
SLATE:
  Instance:
    ID: "untagged"
### SLATE-END ###
