Instance: ""

# Site information that should match the CE Topology registration
Site:
  Group: OSG
  Resource: UCHICAGO-SLATE
  ResourceGroup: UCHICAGO
  Sponsor: osg:100
  Contact: Lincoln Bryant
  ContactEmail: lincolnb@uchicago.edu
  City: Chicago
  Country: US
  Latitude: 41.8781
  Longitude: 87.6298

Cluster:
  # Major Enterprise Linux version of the remote cluster (6 or 7)
  OperatingSystem: 7
  PrivateKeySecret: lincolnb-bosco # maps to SLATE secret

Storage:
  GridDir: $HOME/bosco-osg-wn-client
  WorkerNodeTemp: /tmp

Subcluster:
  Memory: 1024
  CoresPerNode: 4
  MaxWallTime: 1440
  AllowedVOs: osg, cms, atlas, glow, hcc, fermilab, ligo, virgo, sdcc, sphenix, gluex, icecube, xenon
  
Squid:
  Enabled: True
  Location: squid.grid.uchicago.edu
  
Networking:
  # The hostname that the CE should use. 
  # Appropriate A and PTR DNS records must exist.
  Hostname: ""
  # The preferred IP address which should be requested from the LoadBalancer. 
  # This may be left as null to express no preference. 
  # Setting this may be useful when redeploying a CE in order to try to get
  # back the same IP address that was used previously. 
  RequestIP: null

########### REQUIRED ###########
# Specify additional HTCondor-CE configuration. JOB_ROUTER_ENTRIES is required!
# HTCondorCeConfig: |+
#   JOB_ROUTER_ENTRIES =@jre
#   [
#     GridResource = "batch <REMOTE USER>@<REMOTE HOST> <REMOTE BATCH>"
#     Requirements = 'Owner == "<REMOTE USER>"'
#   ]
#   [
#   ...
#   @jre

# Options to allow override of the bosco directory from arbitrary git repos
# Bosco override dirs are expected in the following location in the git repo:
#   <RESOURCE NAME>/bosco_override/
BoscoOverrides:
  Enabled: true
  GitEndpoint: git@gitlab.mwt2.org:osg/hosted-ce-config.git
  RepoNeedsPrivKey: true
  GitKeySecret: mwtGitLabSecret

# Enable a logging sidecar
HTTPLogger:
  Enabled: false

# Default VO-user mappings for OSG Hosted CEs
# Change these contents for legacy OSG Hosted CEs or non-OSG Hosted CEs
VomsmapOverride: |+
  "/osg/Role=NULL/Capability=NULL" osg01
  "/GLOW/Role=htpc/Capability=NULL" osg02
  "/hcc/Role=NULL/Capability=NULL" osg03
  "/cms/*" osg04
  "/fermilab/*" osg05
  "/osg/ligo/Role=NULL/Capability=NULL" osg07
  "/virgo/ligo/Role=NULL/Capability=NULL" osg07
  "/sdcc/Role=NULL/Capability=NULL" osg08
  "/sphenix/Role=NULL/Capability=NULL" osg08
  "/atlas/*" osg09
  "/Gluex/Role=NULL/Capability=NULL" osg10
  "/dune/Role=pilot/Capability=NULL" osg11
  "/icecube/Role=pilot/Capability=NULL" osg12
  "/xenon.biggrid.nl/Role=NULL/Capability=NULL" osg13

# If you wish to allow yourself to submit to this CE with your personal grid
# proxy, you can put that in below. This will get directly mapped into
# /etc/grid-security/grid-mapfile
#
#GridmapOverride: |+
#  "/DC=foo/DC=bar/OU=Organic Units/OU=Users/CN=YourUserName" osg

# FOR DEVELOPMENT PURPOSES ONLY!
# Setting 'Enabled: true' below does the following:
# - Configures the CE as an ITB host
# - Generates a test CA and self-signed host cert/key pair
Developer:
  Enabled: false
