{{ if .Values.ExtraConf.Enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "osg-frontier-squid.fullname" . }}
  labels:
    app: {{ template "osg-frontier-squid.name" . }}
    chart: {{ template "osg-frontier-squid.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}
data:
  99-extra-squid-params.sh: |+
    awk --file `dirname $0`/customhelps.awk --source '{
     setoption("workers", {{ .Values.ExtraConf.Workers }})
     #setoption("max_filedescriptors", "8192")
     setoptionparameter("cache_dir", 2, "/var/cache/squid/squid${process_number}")
     setoption("cpu_affinity_map", {{ .Values.ExtraConf.Cpu_Affinity_Map }})
     setoptionparameter("logformat awstats", 3, "kid${process_number}")
     setoption("visible_hostname", "'`uname -n`'/${process_number}")
     setoption("logfile_rotate", {{ .Values.ExtraConf.Logfile_Rotate }})
     insertline("disable_potential_heap_overflow", "acl URN proto URN")
     insertline("http_access_deny", "http_access deny URN")
     print
    }'
{{ end }}
