apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "osg-frontier-squid.fullname" . }}
  labels:
    app: {{ template "osg-frontier-squid.name" . }}
    chart: {{ template "osg-frontier-squid.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}

spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "osg-frontier-squid.name" . }}
      chart: {{ template "osg-frontier-squid.chart" . }}
      release: {{ .Release.Name }}
      instance: {{ .Values.Instance | quote }}

  template:
    metadata:
      labels:
        app: {{ template "osg-frontier-squid.name" . }}
        chart: {{ template "osg-frontier-squid.chart" . }}
        release: {{ .Release.Name }}
        instance: {{ .Values.Instance | quote }}
    spec:
      nodeSelector:
        # Required affinity for using local storage
        {{ if .Values.SLATE.LocalStorage }}
        storage: "local"
        {{ end }}
        # For Node Selection
        {{ if .Values.NodeSelection.Hostname }}
        kubernetes.io/hostname: {{ .Values.NodeSelection.Hostname }}
        {{ end }}
      containers:
      # Container for the primary application, OSG Frontier Squid
      - name: osg-frontier-squid
        image: opensciencegrid/frontier-squid:fresh
        imagePullPolicy: Always
        env:
        - name: SQUID_IPRANGE
          value: {{ .Values.SquidConf.IPRange }}
        - name: SQUID_CACHE_MEM
          value: '{{ .Values.SquidConf.CacheMem }} MB'  
        ports:
        - containerPort: 3128
          name: squid
        - containerPort: 3401
          name: monitoring
          protocol: UDP
        volumeMounts:
# Commetned out and will probably not be needed. We're using the default 60-image-post-init.sh script 
# that comes with upstream image. Our custom config has been moved to the .awk file added through configmap
#        - name: osg-frontier-squid-{{ .Values.Instance }}-conf
#          mountPath: /etc/osg/image-config.d/60-image-post-init.sh
#          subPath: 60-image-post-init.sh 
        {{ if .Values.SquidConf.LogToStdout }}
        - name: osg-frontier-squid-{{ .Values.Instance }}-conf
          mountPath: /etc/supervisord.d/50-squid-log-dump.conf
          subPath: 50-squid-log-dump.conf 
        {{ end }}
        # Storage location of the cache data
        - mountPath: /var/cache/squid/osg-frontier-squid-{{ .Values.Instance }}-cache
          subPath: osg-frontier-squid-{{ .Values.Instance }}-cache
          name: osg-frontier-squid-{{ .Values.Instance }}-data
        - mountPath: /etc/squid/customize.d/60-customization.awk
          subPath: 60-customization.awk
          name: osg-frontier-squid-{{ .Values.Instance }}-awk
      volumes:
        - name: osg-frontier-squid-{{ .Values.Instance }}-awk
          configMap:
            name: {{ template "osg-frontier-squid.fullname" . }}
            items:
            - key: 60-customization.awk
              path: 60-customization.awk
              mode: 420
        - name: osg-frontier-squid-{{ .Values.Instance }}-conf
          configMap:
            name: {{ template "osg-frontier-squid.fullname" . }}
            items:
            - key: 60-image-post-init.sh
              path: 60-image-post-init.sh
              mode: 448
            {{ if .Values.SquidConf.LogToStdout }}
            - key: 50-squid-log-dump.conf
              path: 50-squid-log-dump.conf
            {{ end }}
        - name: osg-frontier-squid-{{ .Values.Instance }}-data
        {{ if .Values.SLATE.LocalStorage }}
          persistentVolumeClaim:
            claimName: osg-frontier-squid-{{ .Values.Instance }}-pvc
        {{ else }}
          emptyDir: {}
        {{ end }}
