apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "osg-frontier-squid.fullname" . }}
  labels:
    app: {{ template "osg-frontier-squid.name" . }}
    chart: {{ template "osg-frontier-squid.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}

spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "osg-frontier-squid.name" . }}
      chart: {{ template "osg-frontier-squid.chart" . }}
      release: {{ .Release.Name }}
      instance: {{ .Values.Instance | quote }}

  template:
    metadata:
      labels:
        app: {{ template "osg-frontier-squid.name" . }}
        chart: {{ template "osg-frontier-squid.chart" . }}
        release: {{ .Release.Name }}
        instance: {{ .Values.Instance | quote }}
    spec:
      nodeSelector:
        # Required affinity for using local storage
        {{ if .Values.SLATE.LocalStorage }}
        storage: "local"
        {{ end }}
        # For Node Selection
        {{ if .Values.NodeSelection.Hostname }}
        kubernetes.io/hostname: {{ .Values.NodeSelection.Hostname }}
        {{ end }}
      containers:
      # Container for the primary application, OSG Frontier Squid
      - name: osg-frontier-squid
        image: opensciencegrid/frontier-squid:fresh
        imagePullPolicy: Always
        ports:
        - containerPort: 3128
          name: squid
        - containerPort: 3401
          name: monitoring
          protocol: UDP
        env:
        - name: SQUID_IPRANGE
          value: "{{ .Values.SquidConf.IPRange }}"
        - name: SQUID_CACHE_DISK
          value: "{{ .Values.SquidConf.CacheSize }}"
        - name: SQUID_CACHE_MEM
          value: "{{ .Values.SquidConf.CacheMem }} MB"
        volumeMounts:
        {{ if .Values.ExtraConf.Enabled }}
        - name: osg-frontier-squid-{{ .Values.Instance }}-extra-conf
          mountPath: /etc/osg/image-config.d/60-image-post-init.sh
          subPath: 60-image-post-init.sh 
        {{ end }}
        # Storage location of the cache data
        - mountPath: /var/cache/squid/osg-frontier-squid-{{ .Values.Instance }}-cache
          subPath: osg-frontier-squid-{{ .Values.Instance }}-cache
          name: osg-frontier-squid-{{ .Values.Instance }}-data
          # Shared directory for logs with the Fluent-bit sidecar, can be enabled or disabled from values.yaml
      volumes:
        {{ if .Values.ExtraConf.Enabled }}
        - name: osg-frontier-squid-{{ .Values.Instance }}-extra-conf
          configMap:
            name: {{ template "osg-frontier-squid.fullname" . }}
            items:
            - key: 60-image-post-init.sh
              path: 60-image-post-init.sh
              mode: 448
        {{ end }}
        - name: osg-frontier-squid-{{ .Values.Instance }}-data
        {{ if .Values.SLATE.LocalStorage }}
          persistentVolumeClaim:
            claimName: osg-frontier-squid-{{ .Values.Instance }}-pvc
        {{ else }}
          emptyDir: {}
        {{ end }}
