# SLATE Telegraf Monitoring Configuration


# The slate instance value.
Instance: ""


# Optionally write to stdout and local file in container.
writeToStdout: true


# Specifies the default data collection interval.
# Time values can be specified by combining an integer value with a time unit.
# Valid time units include "ns", "us", "ms", "s", "m" and "h".
interval: "5s"


# Specifies time between output flushes.
# Uses the same syntax as the interval parameter.
flushInterval: "300s"


# Specify hosts to monitor here.
# A hostGroup is a group of hosts that share settings. (e.g. community string, oids)
# Hosts can be IP addresses or DNS names.
# Port must also be specififed with a colon after hostname or address. (default is 161)
# Specify oid section according to the Telegraf SNMP plugin format.
# Documentation can be found at: https://github.com/influxdata/telegraf/tree/master/plugins/inputs/snmp.
# The counter64Bit parameter is only relevant if GRNOC output has been enabled.
# Additionally, the OIDs section will be ignored if GRNOC output has been enabled.
# To poll from devices with 32-bit SNMP counters, set this to false.
# To poll from devices with 64-bit SNMP counters, set this to true.
targets:
  - hostGroup:
      community: "public"
      hosts:
        - "127.0.0.1:161"
      counter64Bit: false
      oids: |-
        [[inputs.snmp.field]]
          oid = "DISMAN-EVENT-MIB::sysUpTimeInstance"
          name = "uptime"
  - hostGroup:
      community: "public"
      hosts:
        - "127.0.0.1:161"
        - "localhost:161"
      counter64Bit: true
      oids: |-
        [[inputs.snmp.field]]
          oid = "DISMAN-EVENT-MIB::sysUpTimeInstance"
          name = "uptime"


# Configuration for GlobalNOC database output
# Set enabled flag to true to enable GlobalNOC output.
# Set hostname, username, and password accordingly.
# Note that enabling GRNOC output results in a pre-defined set of
# OIDs being polled, and will override user-specified OIDs.
grnocOutput:
  enabled: true
  hostname: "tsds.hostname.net"
  username: "tsds username"
  password: "tsds password"


# Configuration for InfluxDB (v1) output.
# Set enabled flag to true to enable InfluxDB output.
# Endpoint parameter must specify a protocol (udp or http) and a port.
# Database parameter should be set to the database name.
influxOutput:
  enabled: false
  endpoint: "http://127.0.0.1:9999"
  database: "telegraf"
  httpBasicAuth:
    enabled: false
    username: "telegraf"
    password: "metrics"
