# SLATE Telegraf Monitoring Configuration


# The slate instance value.
Instance: ""


# Optionally write to stdout and local file in container.
writeToStdout: true


# Specifies the default data collection interval.
# Time values can be specified by combining an integer value with a time unit.
# Valid time units include "ns", "us", "ms", "s", "m" and "h".
interval: "5s"


# Specify hosts to monitor here.
# A hostGroup is a group of hosts that share settings. (e.g. community string, oids)
# Hosts can be IP addresses or DNS names.
# Port must also be specififed with a colon after hostname or address. (default is 161)
# Specify oid section according to the Telegraf SNMP plugin format.
# Documentation can be found at: https://github.com/influxdata/telegraf/tree/master/plugins/inputs/snmp.
targets:
  - hostGroup:
      community: "public"
      hosts:
        - "127.0.0.1:161"
      oids: |-
        [[inputs.snmp.field]]
          oid = "DISMAN-EVENT-MIB::sysUpTimeInstance"
          name = "uptime"
  - hostGroup:
      community: "public"
      hosts:
        - "127.0.0.1:161"
        - "localhost:161"
      oids: |-
        [[inputs.snmp.field]]
          oid = "DISMAN-EVENT-MIB::sysUpTimeInstance"
          name = "uptime"


# Configuration for InfluxDB output.
# Set enabled flag to true to enable InfluxDB output.
# Endpoint parameter must specify a protocol (udp or http) and a port.
# Database parameter should be set to the database name.
influxOutput:
  enabled: true
  endpoint: "http://127.0.0.1:9999"
  database: "telegraf"
