apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "check-mk.fullname" . }}
  labels:
    app: {{ template "check-mk.name" . }}
    chart: {{ template "check-mk.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ template "check-mk.name" . }}
      instance: {{ .Values.Instance | quote }}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: {{ template "check-mk.name" . }}
        chart: {{ template "check-mk.chart" . }}
        release: {{ .Release.Name }}
        instance: {{ .Values.Instance | quote }}
    spec:
      containers:
      - env:
        - name: CHECK-MK_CONFIG_STAT_RELOAD
        - name: CHECK-MK_EVENT_SOCK
        image: checkmk/check-mk-raw:1.6.0-latest
        imagePullPolicy: Always
        name: check-mk
        ports:
        - containerPort: {{ .Values.service.internalPort }}
        resources: {}
        volumeMounts:
        - mountPath: /opt/omd/sites/cmk/tmp/
          name: {{ template "check-mk.name" . }}-claim
      restartPolicy: Always
      volumes:
      - name: {{ template "check-mk.name" . }}-claim
        persistentVolumeClaim:
          claimName: {{ template "check-mk.name" . }}
status: {}
