apiVersion: v1
kind: ConfigMap
metadata:
  name: perfsonar-demo-{{ .Values.Instance }}-startup
  labels:
    app: {{ template "perfsonar-testpoint-demo.name" . }}
    chart: {{ template "perfsonar-testpoint-demo.chart" . }}
    release: {{ .Release.Name }}
    instance: {{ .Values.Instance | quote }}
data:
  startup_script.sh: |+
    #!/bin/bash
    whoami
    stat /usr/bin/pscheduler
    echo "*/2 * * * * /usr/bin/run-my-tests.sh > /tmp/cron.out" > /var/spool/cron/root
    sleep 600
#    /usr/local/sbin/supervisord_startup.sh
#    echo "Starting Tests..."
    #/usr/bin/pscheduler task throughput -t 10 --dest sl-um-ps01.slateci.io
    #echo "Done with all tests.." 
#    echo "Sleeping for 3 mins.."
#    sleep 360

  run-my-tests.sh: |+
    #!/bin/bash
    echo "Starting Tests..."
    #/usr/bin/pscheduler task throughput -t 10 --dest sl-um-ps01.slateci.io
    /usr/bin/pscheduler troubleshoot
    echo "Done with all tests.." 
    echo "Sleeping for 3 mins.."
    sleep 360
{{ if .Values.HTTPLogger.Enabled }}
  start-nginx.sh: |+
    #!/bin/bash -e
    apt-get update
    apt-get install openssl -y

    if [ -z $HTPASSWD ]; then
      PASS=$(tr -dc 'a-f0-9' < /dev/urandom | head -c16)
      echo "Your randomly generated logger credentials are"
      echo "**********************************************"
      echo "logger:$PASS"
      echo "**********************************************"
      HTPASSWD="$(openssl passwd -apr1 $(echo -n $PASS))"
    fi

    mkdir -p /etc/nginx/auth
    echo "logger:$HTPASSWD" > /etc/nginx/auth/htpasswd

    echo 'server {
      listen       8080;
      server_name  localhost;
      location / {
        default_type text/plain;
        auth_basic "Restricted";
        auth_basic_user_file /etc/nginx/auth/htpasswd;  
        root   /usr/share/nginx/html;
        autoindex  on;
      }
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
        root   /usr/share/nginx/html;
      }
    }' > /etc/nginx/conf.d/default.conf
    exec nginx -g 'daemon off;'
{{ end }}
